// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

int sum = 0; 
int fibonnacci1=1;
int fibonnacci0=2;
int tempfibonnacci0;
int tempfibonnacci1;

int main (void) {

    while (fibonnacci0 < 4000000) {
        if (fibonnacci0 % 2 == 0) 
            sum += fibonnacci0;

        tempfibonnacci0 = fibonnacci0;
        tempfibonnacci1 = fibonnacci1;
        fibonnacci0 = fibonnacci0 + fibonnacci1;
        fibonnacci1 = tempfibonnacci0;

    };

    printf("Toplam: %i", sum);
    return 0;

}