// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

int product;

int reverseNum(int N) {
  
  	// Function to store the reversed number
    int rev = 0;
    while (N > 0) {

        // Extract the last digit
        int dig = N % 10;

        // Append the digit to the reversed number
        rev = rev * 10 + dig;

        // Remove the last digit
        N /= 10;
    }
    return rev;
}

int isPalindrome(int N) {
    if (N < 0)
        return 0;
    return N == reverseNum(N);
}

int main (void) {
    for (int N1= 999; N1 > 900; N1--) {
        for (int N2=999; N2 > 900; N2--) {
            product = N1*N2;
            if (isPalindrome(product) == 1)
                break;
        };
        if (isPalindrome(product) == 1)
            break;    }
    

    printf ("Largest palindrome is: %d", product);
    return 0;
}